#!/bin/bash
# Example commands to try

echo "🎙️  Podcast Growth Analyzer - Example Commands"
echo "================================================"
echo ""
echo "1. Demo Mode (No API keys needed):"
echo "   python demo.py"
echo ""
echo "2. Search AI/Tech podcasts with \$5k budget:"
echo "   python podcast_analyzer.py -n 'artificial intelligence' -b 5000"
echo ""
echo "3. Business podcasts, detailed analysis:"
echo "   python podcast_analyzer.py -n 'business' -b 10000 --detailed"
echo ""
echo "4. Marketing podcasts, budget-friendly:"
echo "   python podcast_analyzer.py -n 'marketing' -b 2000 -m 50"
echo ""
echo "5. Finance podcasts, high-growth only:"
echo "   python podcast_analyzer.py -n 'finance investing' -b 15000 -m 75"
echo ""
echo "6. Show help:"
echo "   python podcast_analyzer.py --help"
echo ""
echo "================================================"
